### ISSUE TITLE
id number for Colombia

### ISSUE THREAD

**Issue by microdataxyz** [identique/idnumbers#5]
https://en.wikipedia.org/wiki/National_identification_number#Colombia

**Comment by marcilioLemos** [comment]
Any idea about when the Colombia id number will be available? Great project btw!

**Comment by marcilioLemos** [comment]
Any idea about when the Colombia id number will be available? Great project btw!

**Comment by microdataxyz** [comment]
@marcilioLemos let me try to finish it before this release. 😄

**Comment by microdataxyz** [comment]
@marcilioLemos May you provide some information about the ID number, NUIP? I just googled the result:
* It contains 10 digits, from https://validatetin.com/colombia/#
* The last digit is the checksum. It is a weighted value. I could only find the checksum algorithm from there: https://github.com/anghelvalentin/CountryValidator/blob/master/CountryValidator/CountriesValidators/ColombiaValidator.cs#L61

I cannot make sure if there is any sources about the NUIP checksum algorithm. It would be great if you could provide some.

**Comment by microdataxyz** [comment]
@marcilioLemos I make it 9 or 10 digits compatible because the old format has 9 digits including the checksum and the new format has 10 digits including the checksum. 

```
    METADATA = SimpleNamespace(**{
        'iso3166_alpha2': 'CO',
        # length without insignificant chars
        'min_length': 9,
        'max_length': 10,
        # has parse function
        'parsable': False,
        # has checksum function
        'checksum': True,
        # regular expression to validate the id
        'regexp': re.compile(r'^(\d{2,3}\.?\d{3}\.?\d{3}-?\d)$')
    })
```
